apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::521371405940:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-18XXYVOAWDG60
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::521371405940:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-06-17T20:01:41Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "763"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: b3af13b8-0fb7-458f-bb17-268896f43429
